#+BIND: org-export-use-babel nil
#+TITLE: TDA Lab Rotation on ADNI data at the MLCB lab of Prof Borgwardt
#+AUTHOR: Philip Hartout
#+EMAIL: <philip.hartout@protonmail.com>
#+DATE: August 17, 2020
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:[a4paper,12pt,twoside]
#+LaTeX_HEADER:\usepackage[usenames,dvipsnames,figures]{xcolor}
#+LaTeX_HEADER:\usepackage[autostyle]{csquotes}
#+LaTeX_HEADER:\usepackage[final]{pdfpages}
#+LaTeX_HEADER:\usepackage[top=3cm, bottom=3cm, left=3cm, right=3cm]{geometry}
#+LATEX_HEADER_EXTRA:\hypersetup{colorlinks=false, linkcolor=black, citecolor=black, filecolor=black, urlcolor=black}
#+LATEX_HEADER_EXTRA:\newtheorem{definition}{Definition}[section]
#+LATEX_HEADER_EXTRA:\pagestyle{fancy}
#+LATEX_HEADER_EXTRA:\setlength{\headheight}{25pt}
#+LATEX_HEADER_EXTRA:\lhead{\textbf{Philip Hartout}}
#+LATEX_HEADER_EXTRA:\rhead{\textbf{}}
#+LATEX_HEADER_EXTRA:\rfoot{}
#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@
#+PROPERTY: header-args :exports both :session python_emacs_session :cache :results value
#+OPTIONS: ^:nil
#+STARTUP: latexpreview
#+LATEX_COMPILER: pdflatexorg-mode restarted

This is the repository containing a TDA of the ADNI data done in the context of a lab rotation at
the MLCB lab of ETHZ. The goal of this project was fourfold:

1. How salient are the topological features extracted from the patch for the characterization of
  the atrophy observed in Alzheimer's disease as measured through the classification performance of
AD versus CN subjects using persistence images?

2. What does the distance between the persistence image and persistence
landscape of a patient and the median persistence image or landscape of a
diagnostic category reveal about the topological heterogeneity within a given
diagnostic category?

3. How can the distance among persistent images taken for each patient over the course of the
  disease inform us with regard to the progression of the patient during the monitoring period?

4. Does taking the distance between each image and two median persistence
images (from AD patients and CN subjects) allow adequate clustering of patients
in diagnostic categories or disease subtypes?

* Dependencies
All dependencies are managed through [[https://python-poetry.org/][poetry]]. Use `poetry install` to install them.

* Folder structure
This repository is organized as follows:

#+begin_example
├── figures                         # Contains raw figures exported by scripts
├── literature                      # Some useful literature
├── presentation                    # Presentation made to the lab on 2/12/2020
│   ├── figures
│   ├── lab_update.pdf
│   ├── lab_update.tex
│   └── References.bib
├── pyproject.toml                  # Poetry dependencies
├── README.org
├── report                          # Scripts in this directory answer question 4.
│   ├── figures                     # Contains figures compiled in the TeX document for the report exclusively
│   ├── main.bib
│   ├── neurips_2020.sty
│   ├── report_lab_rotation.tex
└── scripts                         # Contains all scripts used in the analysis. Some may need adjustment to work
    ├── clustering                  # Scripts in this directory answer question 4.
    ├── distances_from_median_rep   # Scripts in this directory answer parts question 2.
    ├── global                      # Scripts to produce data yielding the CNN performance for the whole-brain PI
    ├── models                      # Scripts in this directory answer question 1. (also contains models not discussed in the report)
    ├── outliers_misclassified      # Scripts in this directory answer parts of question 2.
    ├── patient_evolution           # Scripts in this directory answer question 3.
    ├── persistent_homology         # Scripts in this directory perform persistent homology on the sMRI, useful for all questions.
    ├── plotting                    # Scripts in this directory produce all the plots in figures/
    └── utils.py                    # Utilities used by multiple scripts.
#+begin_example

#+end_example

* Acknowledgments
I would like to thank [[https://bastian.rieck.me/][Bastian Rieck]] for the supervision, [[https://bsse.ethz.ch/department/people/detail-person.MTg3NjEz.TGlzdC8yNjY5LDEwNjI4NTM0MDk=.html][Catherine Jutzeler]] and [[https://bsse.ethz.ch/mlcb/people/person-detail.MjYyNjM1.TGlzdC83NjcsLTEyNjQ4MzU1MTY=.html][Sarah Brüningk]] for
helpful discussions, and [[https://bsse.ethz.ch/mlcb][Karsten Borgwardt]] for providing the research environment.
